# Project Configuration
spring.application.name=smart-home-automation
server.port=8081

# Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/home_automation_demo
#spring.datasource.username=root
#spring.datasource.password=Kum@resh_12

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/SmartHome
spring.datasource.username=postgres
spring.datasource.password=root123

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Redis Config
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.timeout=60000

# Tell Spring to use Redis for caching
spring.cache.type=redis

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
#spring.jpa.show-sql=true

# JWT secret (Base64) - keep secret in env / vault in production
jwt.secret=ZmFrZV9zZWNyZXRfYmFzZTY0X3NlY3JldF9oZXJlX2NoYW5nZV9pdA==

# pending session lifetime (10 minutes)
pending.session.duration=600000

# access token lifetime (5 minutes)
access.token.duration=300000

# active session lifetime (30 minutes)
active.session.duration=1800000

# refresh token lifetime (7 days)
refresh.token.duration=604800000

# security token lifetime (5 minutes)
security.token.duration=300000

# security code lifetime (2 minutes)
security.code.duration=120000

# security code request boundary time (5 minutes)
security.code.request.boundary.duration=300000

# max security code request per user
max.security.code.request.per.user=2

# CORS allowed origin
allowed.origin=http://localhost:3000,http://127.0.0.1:5502,http://localhost:5173

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testotp2002@gmail.com
spring.mail.password=xmdk tvxb gdtj jyql
spring.mail.name=Home Automation
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Error Message Configuration
authentication.required=Authentication Required!
invalid.or.expired.session=Invalid or expired session. Please log in again.
invalid.or.expired.security.code=Invalid or expired security code. Please try again.
invalid.or.expired.security.token=Invalid or expired security token. Please try again.
already.exist=Already exists.

# Logging Configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.example.smart.home.automation=DEBUG
logging.level.org.springframework.web.socket=TRACE
logging.level.org.springframework.messaging=TRACE
logging.level.org.springframework.web.socket.messaging=TRACE

# MQTT Configuration
mqtt.broker.url=tcp://localhost:1883
mqtt.broker.username=
mqtt.broker.password=

openhab.token=oh.Rias24.62BtENEhwKHKt0WLAFrabqx3piCPvK3GdcXwFd0eUQvwSTAgTqu11SSOwwvGkL87Fb5wFlWLOjrPJ3I91Q